name: CI/CD for TOD app
on:
  push:
    branches: ["main"]
  
jobs:
  #build app, test and push to ecr
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout main branch
      uses: actions/checkout@v3
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ variables.AWS_REGION }}
    - name: build docker image
      run: |
        echo "pass"
        echo "pass2"
      
      
  #deploy to staging
  
  #deploy to prod


