name: CI/CD for TOD app
on:
  push:
    branches: ["main"]
  
jobs:
  #build app, test and push to ecr
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: checkout main branch
      uses: actions/checkout@v3
    - name: build docker image
      run: |
        echo "pass"
        echo "pass2"
      
      
  #deploy to staging
  
  #deploy to prod


