name: test workflow
on:
  workflow_dispatch
jobs:
  create_secret:
    runs-on: ubuntu-22.04
    outputs:
      image: ${{ steps.make_var.outputs.image }}
    steps:
    - name: make var
      id: make_var
      run: |
        the_secret="blahblah"
        echo $the_secret
        echo "::add-mask::$the_secret"
        echo "::set-output name=image::$the_secret"
        #echo "image=$the_secret" >> $GITHUB_OUTPUT
    - name: use var
      run: echo ${{ steps.make_var.outputs.image}}
    
  use_secret:
    runs-on: ubuntu-22.04
    needs: create_secret
    steps:
    - name: use var
      run: echo ${{ needs.create_secret.outputs.image}}
